### ISSUE TITLE
make item inactive/active

### ISSUE THREAD

**Issue by tkntobfrk** [SplitmediaLabsLimited/xui#6]
I know theres a newer version of the framework, but I haven't had a chance to port/look at it yet.

With this framework how difficult is it to enable/disable an item? For example if I wanted to make a Text item inactive on the scene?

I couldn't find anything that would do it in this api, is it possible or should I stop my search?

**Comment by dcefram** [comment]
Yes, that's missing on this framework. You could however make use of the internal module to manually set it.

- First get the item id of the item that you want to hide.
- Attach that item id using internal.Item.attach(id, 0); // 0 is the viewID
- set the `prop:visible` to 0 using internal.Item.set('prop:visible', 0); // 0 for hide, 1 for show

I would however recommend that you try out using the xjs framework since it's much more 'complete' than this framework :)

**Comment by tkntobfrk** [comment]
This doesn't actually work.

var slot = internal.Item.attach(id, 0);
internal.Item.set('prop:visible', itemString, slot);

it updates the value, but the change doesnt get reflected in xsplit. ie. things dont disappear when set to 0.  I'm looking at updating the fuctions I have with the new xjsframework version, will post any issues there.

**Comment by dcefram** [comment]
Sorry, I made a mistake there. You should send a string '0' instead of a integer 0 to internal item set. ie. internal.Item.set('prop:visible', '0', slot);

But since you are migrating to xjs framework, it would be as simple as using setVisible(false);

**Comment by tkntobfrk** [comment]
oh tried set visible in new framework, so much cleaner. Ill check it out a bit more

**Comment by dcefram** [comment]
Cool :) will close this then :D
